### ISSUE TITLE
Design and interface review

### ISSUE THREAD

**Issue by pdswan** [pdswan/unsound#2]
Opening up a discussion around the existing code and [integration with rom](https://github.com/rom-rb/rom/pull/177).

**Comment by solnic** [comment]
I started using it in my project at work and stumbled on #3 issue. Other than that this seems like a good direction, I really like how the code is structured when using unsound. Could you fix the issue I reported? I'm looking forward to trying it out in more places but this one's blocking me.

**Comment by pdswan** [comment]
@solnic have you played with this anymore? curious to hear how you're finding it.

**Comment by solnic** [comment]
@pdswan no :( I had to move to another project where it's not used. I'll try it out again in my personal stuff though. Right now I'm focusing on mapping stuff in ROM for its 0.7.0. After that commands will become a priority again so I'll be spending more time on Unsound and its integration.

**Comment by pdswan** [comment]
@solnic cool. Been looking for a good place to jump in on 0.7.0 issues,
hope to contribute soon.

**Comment by solnic** [comment]
You may want to check out our waffle board. Essentially everything in
“Ready” column is ready for development. Please let me know if you’d like
to tackle something :)
